### ISSUE TITLE
Example or docs entry for using w/TLS?

### ISSUE THREAD

**Issue by ahorwitz** [clojurewerkz/machine_head.docs#7]
Thanks for the library!

Doing basic connect, pub/sub and authentication was pretty straightforward from looking at docs/source. Cool! However, I'm using Mosquitto and tlsv1 w/a self-signed cert & it's not immediately apparent how to connect over TLS.  

I'm not too familiar with Paho (& the Java ecosystem in general). From looking around on SO it seems this is handled by the JVM, by adding certs to ```$JAVA_HOME/jre/lib/security``` .

I haven't actually tried it yet, but if it works I would be happy to submit an example. And if there is a more sound way to approach this I would definitely be interested in it!

**Comment by michaelklishin** [comment]
There are many aspects to establishing TLS connections. This is not a TLS support forum, for Paho Java or in general. Contributions and issues with more details about specific limitatations are definitely welcome.
